### ISSUE TITLE
Add rule for a new line at the end of each file

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/eslint-config-lisk-base#10]
There should be a rule in eslint-config, that ensures that every file ends with a new line.

see: https://eslint.org/docs/rules/eol-last

**Comment by willclarktech** [comment]
This is already included as part of the `eslint-config-airbnb-base` which we extend:
https://github.com/airbnb/javascript/blob/2676cbfb2f9cae832f02f0ea43a9df3f024a24f9/packages/eslint-config-airbnb-base/rules/style.js#L63
